server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: 1234
      database: UserProfileDB
      uri: mongodb://admin:1234@localhost:27017/
